{
  "comments": [
    {
      "key": {
        "uuid": "4a14079a_f02ad09f",
        "filename": "resources/libraries/python/ssh.py",
        "patchSetId": 5
      },
      "lineNbr": 123,
      "author": {
        "id": 76
      },
      "writtenOn": "2018-05-11T09:06:14Z",
      "side": 1,
      "message": "Still not clear what exception can this close() throws.",
      "range": {
        "startLine": 123,
        "startChar": 12,
        "endLine": 123,
        "endChar": 23
      },
      "revId": "00cc4705d49be2219e47a8aad5eeecebc28d94d1",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": false
    }
  ]
}