{
  "comments": [
    {
      "key": {
        "uuid": "1a047c33_b5907a8a",
        "filename": "resources/tools/presentation/generator_alerts.py",
        "patchSetId": 9
      },
      "lineNbr": 251,
      "author": {
        "id": 1263
      },
      "writtenOn": "2021-07-28T11:11:52Z",
      "side": 1,
      "message": "No need to return this, the caller has access to self.error_msgs already.",
      "range": {
        "startLine": 251,
        "startChar": 59,
        "endLine": 251,
        "endChar": 79
      },
      "revId": "98e5d3c8313dd3637fa635ed43246fea8d0ccade",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": true
    }
  ]
}